name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

# Tên profile sẽ được sử dụng để kết nối, khớp với file profiles.yml
profile: 'docker_pipeline_profile'

# Cấu hình đường dẫn cho các loại file khác nhau
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Cấu hình mặc định cho các models
models:
  # Ví dụ: tất cả các model trong thư mục staging sẽ được material hóa thành view
  staging:
    +materialized: table
  intermediate:
    +materialized: table
  marts:
    +materialized: table