# .github/workflows/ci.yaml
name: dbt Core CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  dbt_debug_check:
    name: Run dbt debug
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Start all services in the background
        run: docker-compose up --build -d

      - name: 3. Wait for services to become healthy
        run: |
          echo "Waiting for services to start..."
          # Đợi cho đến khi dbt_clickhouse và airflow-webserver ở trạng thái 'healthy'
          # Thay vì sleep 30s, cách này thông minh và đáng tin cậy hơn
          end_time=$((SECONDS+120)) # Đợi tối đa 2 phút
          while [ $SECONDS -lt $end_time ]; do
            if [[ "$(docker-compose ps -q dbt_clickhouse)" && \
                  "$(docker-compose ps dbt_clickhouse | grep -c '(healthy)')" -eq 1 && \
                  "$(docker-compose ps -q airflow-webserver)" && \
                  "$(docker-compose ps airflow-webserver | grep -c '(healthy)')" -eq 1 ]]; then
              echo "All services are healthy!"
              break
            fi
            sleep 5
            echo -n "."
          done
          if [ $SECONDS -ge $end_time ]; then
            echo "Services did not become healthy in time."
            docker-compose logs
            exit 1
          fi

      - name: 4. Run dbt debug command
        run: |
          docker-compose exec -T -w /opt/dbt_project airflow-webserver dbt debug --target docker_pipeline

      - name: 5. Stop all services
        if: always() # Luôn chạy bước này dù bước trên thành công hay thất bại
        run: docker-compose down