# .github/workflows/ci.yaml
name: dbt Core CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  dbt_debug_check:
    name: Run dbt debug
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./data-pipeline-stack

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Verify Docker Compose
        run: |
          echo "🐳 Checking Docker Compose version..."
          docker compose version

      - name: 3. Fix permissions for dbt directories
        run: |
          echo "🔧 Setting up permissions for dbt project..."
          # Tạo directories nếu chưa có
          mkdir -p dbt_project/logs dbt_project/target
          
          # Set ownership cho airflow user (UID 50000)
          sudo chown -R 50000:0 dbt_project/
          
          # Set permissions để airflow user có thể ghi
          sudo chmod -R 775 dbt_project/
          
          echo "✅ Permissions configured:"
          ls -la dbt_project/

      - name: 4. Start all services in the background
        run: |
          echo "🚀 Starting services with docker compose..."
          docker compose up --build -d
          echo "✅ Services started"

      - name: 5. Wait for services to become healthy
        run: |
          echo "⏳ Waiting for services to become healthy..."
          end_time=$((SECONDS+180))
          
          while [ $SECONDS -lt $end_time ]; do
            echo "🔍 Checking services health... (${SECONDS}s elapsed)"
            
            # Show current status
            docker compose ps
            echo ""
            
            # Check if both services are healthy
            if docker compose ps | grep -q "dbt_clickhouse.*healthy" && \
               docker compose ps | grep -q "airflow-webserver.*healthy"; then
              echo "✅ All services are healthy!"
              break
            fi
            
            echo "⏳ Services not ready yet, waiting..."
            sleep 10
          done
          
          if [ $SECONDS -ge $end_time ]; then
            echo "❌ Services did not become healthy in time."
            echo ""
            echo "📊 Final container status:"
            docker compose ps
            echo ""
            echo "📜 Container logs (last 100 lines):"
            docker compose logs --tail=100
            exit 1
          fi

      - name: 6. Verify dbt setup and permissions
        run: |
          echo "🔍 Checking dbt project structure..."
          docker compose exec -T airflow-webserver ls -la /opt/dbt_project/
          echo ""
          echo "🔍 Checking logs directory permissions..."
          docker compose exec -T airflow-webserver ls -la /opt/dbt_project/logs/ || echo "⚠️ logs directory not accessible"
          echo ""
          echo "📄 Checking dbt_project.yml..."
          docker compose exec -T airflow-webserver cat /opt/dbt_project/dbt_project.yml
          echo ""
          echo "📄 Checking profiles.yml..."
          docker compose exec -T airflow-webserver cat /opt/dbt_project/profiles.yml || echo "⚠️ profiles.yml not found"
          echo ""
          echo "👤 Checking current user in container..."
          docker compose exec -T airflow-webserver whoami
          docker compose exec -T airflow-webserver id

      - name: 7. Run dbt debug command
        run: |
          echo "🔧 Running dbt debug..."
          docker compose exec -T -w /opt/dbt_project airflow-webserver dbt debug --target docker_pipeline

      - name: 8. Show logs on failure
        if: failure()
        run: |
          echo "❌ Job failed! Showing logs for debugging..."
          echo ""
          echo "📜 Airflow webserver logs:"
          docker compose logs --tail=200 airflow-webserver
          echo ""
          echo "📜 ClickHouse logs:"
          docker compose logs --tail=100 dbt_clickhouse

      - name: 9. Stop all services
        if: always()
        run: |
          echo "🛑 Stopping all services..."
          docker compose down -v
          echo "✅ Cleanup complete"