name: dbt Core CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  dbt_debug_check:
    name: Run dbt debug
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./data-pipeline-stack

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Verify Docker Compose
        run: |
          echo "Checking Docker Compose version..."
          docker compose version

      - name: 3. Start all services
        env:
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: clickhouse_password
          CLICKHOUSE_DB: default
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
          AIRFLOW_UID: 50000
          AIRFLOW_GID: 0
          _AIRFLOW_WWW_USER_PASSWORD: airflow
          AIRFLOW_SECRET_KEY: test_secret_key_for_ci
        run: |
          echo "Starting services..."
          docker compose up --build -d
          echo "Services started"

      - name: 4. Wait for services to become healthy
        run: |
          echo "Waiting for services..."
          end_time=$((SECONDS+180))
          
          while [ $SECONDS -lt $end_time ]; do
            echo "Checking health... (${SECONDS}s)"
            docker compose ps
            echo ""
            
            if docker compose ps | grep -q "dbt_clickhouse.*healthy" && \
               docker compose ps | grep -q "airflow-webserver.*healthy"; then
              echo "All services healthy!"
              break
            fi
            
            sleep 10
          done
          
          if [ $SECONDS -ge $end_time ]; then
            echo "Timeout waiting for services"
            docker compose ps
            docker compose logs --tail=100
            exit 1
          fi

      - name: 5. Fix dbt_project permissions inside container
        run: |
          echo "Fixing permissions inside container..."
          docker compose exec -T --user root airflow-webserver bash -c "
            mkdir -p /opt/dbt_project/logs /opt/dbt_project/target && \
            chown -R 50000:0 /opt/dbt_project && \
            chmod -R 775 /opt/dbt_project && \
            ls -la /opt/dbt_project/
          "

      - name: 6. Verify git installation
        run: |
          echo "Verifying git installation..."
          docker compose exec -T airflow-webserver which git
          docker compose exec -T airflow-webserver git --version

      - name: 7. Run dbt debug
        run: |
          echo "Running dbt debug..."
          docker compose exec -T -w /opt/dbt_project airflow-webserver dbt debug --target docker_pipeline

      - name: 8. Show logs on failure
        if: failure()
        run: |
          echo "Showing logs..."
          docker compose logs --tail=200 airflow-webserver
          docker compose logs --tail=100 dbt_clickhouse
          docker compose logs --tail=100 postgres

      - name: 9. Cleanup
        if: always()
        run: |
          echo "Cleaning up..."
          docker compose down -v
          echo "Cleanup complete"